version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Application.Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=https://jsonplaceholder.typicode.com
    restart: always
    ports:
      - '3000:3000'
    command: 'yarn start'
